// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ychuzkpkdaqaztlawowi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljaHV6a3BrZGFxYXp0bGF3b3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDM0NTcsImV4cCI6MjA3NDU3OTQ1N30.ewRVZUg_bg-l4ZVMJTOenkQU38wOWohIxWJrNup06UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});